[package]
name = "slot-android"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "slot_android"
crate-type = ["cdylib"]

[dependencies]
slot-gfx = { path = "../slot-gfx", default-features = false }
slot-store = { path = "../slot-store" }
slot-ui = { path = "../slot-ui" }
slot-retro = { path = "../slot-retro" }

jni = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
